// Code generated by sqlc. DO NOT EDIT.

package infrastructure

import (
	"context"
	"database/sql"
)

type Querier interface {
	GetUser(ctx context.Context, username sql.NullString) (User, error)
}

var _ Querier = (*Queries)(nil)
