// Code generated by sqlc. DO NOT EDIT.
// source: user.sql

package infrastructure

import (
	"context"
	"database/sql"
)

const getUser = `-- name: GetUser :one
SELECT id, username, email, password, hashed_password, role, created_at, updated_at
FROM "user"
WHERE username = $1
LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, username sql.NullString) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.HashedPassword,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
