DROP TABLE IF EXISTS "user" CASCADE;
DROP TABLE IF EXISTS user_account CASCADE;
DROP TABLE IF EXISTS user_address CASCADE;
DROP TABLE IF EXISTS healt_agency CASCADE;
DROP TABLE IF EXISTS health_agency_address CASCADE;
DROP TABLE IF EXISTS check_up CASCADE;
DROP TABLE IF EXISTS patient_queue CASCADE;
DROP TABLE IF EXISTS patient_result CASCADE;